print('hello world')
print('Hassan Ashraf')
print('1,2,3')
print('Hello\nworld')
print('Hello world')
print('apple, banana, cherry')
print('1-2-3')
print('Hello World')
print('1\n2')
print('Hello!')
print('Hassan\Ashraf')
print("'I am 19 year old'.")
print("'THe number is 5.'")
print('1 \n2\n3\n4\n5')